### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by n0ise9914**
Hello Mr Legotin,
I have implemented challenge resolving methods while ago but i've seen you're not maintaining the project anymore, according to your recent activities...
FYI, Instagram is recently forcing users to solve challenges (via geoip detection)
The implemented features are working very well, wish you accept my pr
&Also sorry for ugly codes, need's your cleaning xX
```
//reset challenge
var reset = await _instaApi.ResetChallenge();
//getVerifyStep1
var getVerfiyStep1 = await _instaApi.GetVerifyStep();
//chooseVerfiyMethod (mobile)
var chooseVerfiyMethod = await _instaApi.ChooseVerifyMethod(0);
//getVerifyStep2
var getVerfiyStep2 = await _instaApi.GetVerifyStep();
var code = Console.ReadLine();
//send verify code
var sendCode = await _instaApi.SendVerifyCode(code);
var getVerfiyStep3 = await _instaApi.GetVerifyStep();
```

### CODE REVIEW

**Review by a-legotin — APPROVED** [review]

**Comment by a-legotin** [comment]
Hello @n0ise9914 ! Thanks for you PR, i merge it now into develop and will clean up later on.

**Comment by n0ise9914** [comment]
Hi Alexander ! you're welcome chief 😏

**Comment by DimasHipHop** [comment]
Can you please give me a sample how to send all requests correctly ?

**Comment by ghost** [comment]
If 2FA is enabled, sendverifycode () throw an exception
[Source object is null]

**Pull request merged**
