### PR TITLE
make StartFromId(string nextId) method as static

### PR DESCRIPTION
**Pull request by Marjani**

### CODE REVIEW

**Review by a-legotin — COMMENTED** [review]
Why it needed?
Why you return 'this' from static method?

**Comment by Marjani** [comment]
I want to use this method like:
`                var paging = PaginationParameters.StartFromId("xxxx");
`

**Comment by a-legotin** [comment]
Use PaginationParameters.MaxPagesToLoad(10).StartFromId("xxx") instead or made proper changes, project didnt even build with you change.

**Comment by Marjani** [comment]
I'm sorry for my bad English
what can I do when need all medias after id=xxx? whiteout pages.

**Comment by a-legotin** [comment]
pass int.maxvalue as amount of pages to retrieve

**Pull request closed without merging**
